name: VixFix Scanner

on:
  schedule:
    - cron: '0 * * * *'  # Jede Stunde
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Repository auschecken
        uses: actions/checkout@v3

      - name: Python installieren
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Abhängigkeiten installieren
        run: |
          python -m pip install --upgrade pip
          pip install yfinance pandas numpy

      - name: Skript ausführen
        run: python main.py

      - name: Änderungen committen und pushen (nur bei Änderungen)
        env:
          REPO_URL: https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }}.git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git fetch origin
          git checkout main
          git add vixfix_green.json

          # Prüfen, ob es Änderungen gibt
          if git diff --cached --quiet; then
            echo "Keine Änderungen an der Datei – kein Commit nötig."
          else
            git commit -m "Update JSON"
            git push "$REPO_URL" main
          fi
